basePath: /
definitions:
  models.ErrorModel:
    properties:
      code:
        type: integer
      desc:
        type: string
      error:
        type: string
      internal:
        type: object
    type: object
  models.Post:
    properties:
      author:
        type: string
      content:
        type: string
      id:
        type: string
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: progjb@gmail.com
    name: Rishat Ishbulatov
  description: Blog server with swagger and tests for handlers.
  license:
    name: MIT
  title: Mongoblog server
  version: "1.0"
paths:
  /:
    get:
      description: returns index page with max 20 posts
      produces:
        - text/html
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: serve index templated page
  /api/v1/docs/swagger.json:
    get:
      description: Returns swagger's json docs
      produces:
        - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: returns json docs
  /api/v1/posts:
    post:
      description: create new post and return json
      parameters:
        - description: title, author, content
          in: body
          name: post
          required: true
          schema:
            $ref: "#/definitions/models.Post"
            type: object
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: create new post
  /api/v1/posts/{id}:
    delete:
      consumes:
        - application/json
      description: deletes a post by id
      parameters:
        - description: id
          in: path
          name: id
          required: true
          type: string
        - description: id
          in: body
          name: post
          required: true
          schema:
            $ref: "#/definitions/models.Post"
            type: object
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: deletes a post by id
    put:
      consumes:
        - application/json
      description: renew post by id
      parameters:
        - description: id
          in: path
          name: id
          required: true
          type: string
        - description: title, author, content
          in: body
          name: post
          required: true
          schema:
            $ref: "#/definitions/models.Post"
            type: object
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: renew post by id
  /edit/{id}:
    get:
      description: returns page with edit post form
      parameters:
        - description: id
          in: path
          name: id
          required: true
          type: string
      produces:
        - text/html
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: serve edit post templated page
  /new:
    get:
      description: returns page with new post form
      produces:
        - text/html
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: serve new post templated page
  /view/{id}:
    get:
      description: returns page with one post by id
      parameters:
        - description: id
          in: path
          name: id
          required: true
          type: string
      produces:
        - text/html
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: serve view post templated page
swagger: "2.0"
